# the grammar specification for TUPLE

firstSet = {"program":{"<dt"},
        "paramList":{"<dt"},
        "pList":{",>", "epsilon"},
        "stmts":{"<dt", "<id", "for>", "if>", "return>", "epsilon"},
        "stmtsPrime":{"<dt", "<id", "for>", "if>", "return>", "epsilon"},
        "decStmts":{"<dt"},
        "list":{",>"},
        "optionalAssign":{"=>"},
        "assignStmt":{"<id"},
        "expr":{"(>", "<id"},
        "ePrime":{"+>", "epsilon"},
        "t":{"(>", "<id"},
        "tPrime":{"*>", "epsilon"},
        "f":{"(>", "<id"},
        "forStmt":{"for>"},
        "type":{"<dt", "epsilon"},
        "ifStmt":{"if>"},
        "optionalElse":{"else>"},
        "returnStmt":{"return>"}}

followSet = {"program":{"<$>"},
        "paramList":{")>"},
        "pList":{")>"},
        "stmts":{"}>"},
        "stmtsPrime":{"}>"},
        "decStmts":{"<dt", "<id", "for>", "if>", "return>", "}>"},
        "list":{"<dt", "<id", "for>", "if>", "return>", "}>"},
        "optionalAssign":{",>", "<dt", "<id", "for>", "if>", "return>", "}>"},
        "assignStmt":{"<dt", "<id", "for>", "if>", "return>", "}>"},
        "expr":{";>", ")>", "<rel_op"},
        "ePrime":{";>", ")>", "<rel_op"},
        "t":{"+>", ";>", ")>", "<rel_op"},
        "tPrime":{"+>", ";>", ")>", "<rel_op"},
        "f":{"*>", "+>", ";>", ")>", "<rel_op"},
        "forStmt":{"<dt", "<id", "for>", "if>", "return>", "}>"},
        "type":{"<id"},
        "ifStmt":{"<dt", "<id", "for>", "if>", "return>", "}>"},
        "optionalElse":{"<dt", "<id", "for>", "if>", "return>", "}>"},
        "returnStmt":{",>", "<dt", "<id", "for>", "if>", "return>", "}>"}}